### ISSUE TITLE
注册表方法疑似失效，需要互换文件夹名

### ISSUE THREAD

**Issue by ackerx** [lintx/MapleStoryWebStart#1]
@20220612 
测试发现，原修改注册表的方法，即修改HKLM\software\gamania\maplestory下path路径，并不能影响网页启动时启动的程序。
使用该工具同样无效。
猜测橘子的bfwebstart程序可能事先获得了gamania的安装位置，之后便不再读取path键值。
结合该工具的修正方法：
1、使用一次setting.exe，目的是建立注册表键值gamePath
2、修改mapelstory文件夹名，记作$actual
3、将本工具文件夹挪至原maplestory处，更名为maplestory
4、进注册表，修改HKLM\software\gamania\maplestory下gamePath路径，指向$actual
5、建议修改path，使得与gamePath不同，没做进一步测试。
上述修改后，bfwebstart默认启动maplestory下的本工具，本工具读取gamePath键值，即$actual下的maplestory.exe。实测成功。

作者好心把这问题也解决一下吧，嘿嘿。如果是我的环境的问题，各位有遇到疑问的也可以参考本issue。
测试环境win7 x64 sp1+ firefox 101.0.1

**Comment by lintx** [comment]
重构了
